### ISSUE TITLE
Support for Umbraco 10

### ISSUE THREAD

**Issue by ThomasBaek** [umbraco/Umbraco.StorageProviders#38]
Currently testing for Umbraco 10 RC, and it seems like we need an update here.
Is there anything planned on when to have an update ready?

`An unhandled exception occurred while processing the request.
MissingMethodException: Method not found: 'System.String SixLabors.ImageSharp.Web.FormatUtilities.GetExtensionFromUri(System.String)'.
Umbraco.StorageProviders.AzureBlob.Imaging.AzureBlobFileSystemImageProvider.IsValidRequest(HttpContext context)`

**Comment by ronaldbarendse** [comment]
Version 1 of this package only supports Umbraco 9 and ImageSharp.Web 1 because of the breaking changes introduced in both new major versions (hence the `MissingMethodException`).

The work required to support Umbraco 10 and ImageSharp.Web 2 had already started in PR https://github.com/umbraco/Umbraco.StorageProviders/pull/36 (I've now updated the title to reflect this) and since this got merged today, expect a 2.0.0-rc1 release to be be available very soon!

**Comment by ronaldbarendse** [comment]
Nightly builds are available on our [MyGet feed (including a test release of 2.0.0-rc1)](https://our.umbraco.com/Documentation/Fundamentals/Setup/Install/installing-nightly-builds) and we expect to publicly release this RC together with Umbraco 10.0.0-rc2.

**Comment by alanwthom** [comment]
That's super @ronaldbarendse, thanks. I've got that, so will take it for a spin.
