### ISSUE TITLE
Add / Configure via composer

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco.StorageProviders#56]
As in the Umbraco.Cloud version of this, it would be easier to setup by using a composer like this:

https://github.com/umbraco/Umbraco.Cloud.StorageProviders.AzureBlob/commit/350adf070240afcbfb734ffaf74766745536c5ed

The reasoning for this is that when you work locally, you would then need the code to check for environment before calling `.AddAzureBlobFileSystem`

```diff
public void ConfigureServices(IServiceCollection services)
{
    services.AddUmbraco(_env, _config)
        .AddBackOffice()
        .AddWebsite()
        .AddComposers()
+       .AddAzureBlobMediaFileSystem()
        .Build();
}
```

Would then be (like)

```diff
public void ConfigureServices(IServiceCollection services)
{
    var umbraco = services.AddUmbraco(_env, _config)
        .AddBackOffice()
        .AddWebsite()
        .AddComposers();
+        if(!_env.IsEnvironment("local")){
+                umbraco.AddAzureBlobMediaFileSystem()
+        }
+        umbraco.Build();
}
```

The composer in the Umbraco.Cloud version checks if the configuration is in place, before calling  `.AddAzureBlobMediaFileSystem()`

**Comment by ronaldbarendse** [comment]
I've now added an example site in PR https://github.com/umbraco/Umbraco.StorageProviders/pull/61 that uses a composer to add/configure the services and you can otherwise use the example from the above comment to conditionally add it.

The main reasoning is that this type of configuration relies on external infrastructure and shouldn't change based on the absence of a configuration section/variable. Falling back to the default physical media file system could result in hard to debug runtime issues, especially when using load balancing and/or if you have limited local storage.
